# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies and build the project
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Deploy to GitHub Pages using gh-pages
- script: |
    npm install --save gh-pages
    npm run deploy
  displayName: 'Deploy to GitHub Pages'

